# on: 
#   pull_request:
#     branches:
#       - master

name: Terraform Checks

on: 
  pull_request:
    branches:
      - master


jobs:
  terraform:
    name: Run Terraform Checks
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Install dependencies
      run: |
        sudo apt-get update
        sudo apt-get install -y build-essential
        /bin/bash -c "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/HEAD/install.sh)"
        echo 'eval "$(/home/linuxbrew/.linuxbrew/bin/brew shellenv)"' >> $HOME/.bashrc
        echo 'eval "$(/home/linuxbrew/.linuxbrew/bin/brew shellenv)"' >> $HOME/.profile
        eval "$(/home/linuxbrew/.linuxbrew/bin/brew shellenv)"
      shell: bash

    - name: Set up Homebrew environment
      run: |
        echo "HOMEBREW_PREFIX=$(brew --prefix)" >> $GITHUB_ENV
        echo "HOMEBREW_CELLAR=$(brew --cellar)" >> $GITHUB_ENV
        echo "HOMEBREW_REPOSITORY=$(brew --repository)" >> $GITHUB_ENV
        echo "PATH=$(brew --prefix)/bin:$(brew --prefix)/sbin:$PATH" >> $GITHUB_ENV
        eval "$(/home/linuxbrew/.linuxbrew/bin/brew shellenv)"
      shell: bash

    - name: Set up Terraform
      uses: hashicorp/setup-terraform@v2
      with:
        terraform_version: 1.2.0 # Specify the Terraform version you want to use

    - name: Install TFLint
      run: |
        brew install tflint
      env:
        HOMEBREW_NO_AUTO_UPDATE: 1

    - name: Install TFSec
      run: |
        brew install tfsec
      env:
        HOMEBREW_NO_AUTO_UPDATE: 1

    - name: Terraform Init
      working-directory: challenge-3
      run: terraform init

    - name: Terraform Validate
      working-directory: challenge-3
      run: terraform validate

    - name: Run TFLint
      working-directory: challenge-3
      run: tflint

    - name: Run TFSec
      working-directory: challenge-3
      run: tfsec .
