name: Terraform Checks

on: 
  pull_request:
    branches:
      - master

jobs:
  terraform:
    name: Run Terraform Checks
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Set up Homebrew
      run: |
        /bin/bash -c "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/HEAD/install.sh)"

    - name: Set up Terraform
      uses: hashicorp/setup-terraform@v3
      with:
        terraform_version: 1.2.0 # Specify the Terraform version you want to use

    - name: Set up TFLint
      run: |
        brew install tflint

    - name: Set up TFSec
      run: |
        brew install tfsec

    - name: Terraform Init
      working-directory: challenge-3
      run: terraform init

    - name: Terraform Validate
      working-directory: challenge-3
      run: terraform validate

    - name: Run TFLint
      working-directory: challenge-3
      run: tflint

    - name: Run TFSec
      working-directory: challenge-3
      run: tfsec .
